//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace PastaOrderfood.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetail = new HashSet<OrderDetail>();
        }
    
        public int order_id { get; set; }
        public string order_name { get; set; }
        public string order_phone { get; set; }
        public string order_location { get; set; }
        public string order_email { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public string order_status { get; set; }
        public string order_fn { get; set; }
        public string order_payFn { get; set; }
        public Nullable<int> order_total { get; set; }
        public Nullable<int> isLogin { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public ICollection<OrderDetail> OrderDetail { get; set; }
    }
}
